version: "3.9"

services:
  database:
    container_name: real-world-app-database
    image: mysql:8.1.0
    environment:
      MYSQL_DATABASE: realworld
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "13306:3306"

  backend:
    container_name: real-world-app-backend
    image: back-end-srv
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://database:3306/realworld?serverTimezone=Asia/Seoul&autoReconnect=true&characterEncoding=UTF-8&rewriteBatchedStatements=true"
    depends_on:
      - database


